PeSarana/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls'), name='authentication'),
]

authentication/urls.py
from django.urls import path

from .views import login, signup

urlpatterns = [
    path('login/', login, name='login'),
    path('signup/', signup, name='signup'),
]

authentication/models.py
from django.db import models

# Create your models here.

classroom/models.py
from django.db import models

# Models
from core.models import TimeStampModel

# Create your models here.
class Classroom(TimeStampModel):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField()

core/models.py
from django.db import models

# Create your models here.
class TimeStampModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

student/models.py
from django.db import models

# Models
from core.models import TimeStampModel
from classroom.models import Classroom
from user.models import User

# Create your models here.
class Student(TimeStampModel):
    nisn = models.CharField(max_length=10, unique=True)
    name = models.CharField(max_length=255)
    dob = models.DateField()
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.SET_NULL)

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.base_user import BaseUserManager

# Create your models here.
class UserManager(BaseUserManager):
    def create_user(self, email, name, password=None, **extra_fields):
        if not email:
            raise ValueError("Email wajib diisi")
        email = self.normalize_email(email)
        user = self.model(email=email, name=name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, name, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, name, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=255)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    class Roles(models.TextChoices):
        ADMIN = 'ADMIN', 'Admin'
        STUDENT = 'STUDENT', 'Student'
    
    role = models.CharField(max_length=10, choices=Roles.choices, default=Roles.STUDENT)

    def is_admin(self) -> bool:
        return self.role == self.Roles.ADMIN

    def is_student(self) -> bool:
        return self.role == self.Roles.STUDENT

    def __str__(self):
        return self.email

authentication/forms.py
from django import forms

class SignUpForm(forms.Form):
    nisn = forms.CharField(max_length=10, required=True)
    dob = forms.DateField(required=True)
    email = forms.EmailField(required=True, max_length=255)
    password = forms.CharField(widget=forms.PasswordInput, required=True, min_length=8, max_length=255)

authentication/views.py
from django.shortcuts import render, redirect

from django.http import HttpRequest, HttpResponseRedirect, HttpResponse
from django.contrib.auth.hashers import make_password, check_password

from student.models import Student
from user.models import User

from .forms import SignUpForm

# Create your views here.
def login(request: HttpRequest):
    return render(request=request, template_name='login.html')

def signup(request: HttpRequest) -> HttpResponse | HttpResponseRedirect:
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            nisn = form.cleaned_data['nisn']
            dob = form.cleaned_data['dob']
            student = Student.objects.filter(nisn=nisn).first()
            if not student:
                form.add_error('nisn', 'NISN tidak ditemukan.')
            elif student.user:
                form.add_error('nisn', 'NISN sudah terikat dengan akun.')
            elif student.dob != dob:
                form.add_error('dob', 'Tanggal lahir tidak cocok.')
            else:
                user = User.objects.create_user(
                    name=student.name,
                    email=form.cleaned_data['email'],
                    password=form.cleaned_data['password'],
                    role=User.Roles.STUDENT
                )
                student.user = user
                student.save()
                return redirect('login')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

authentication/templates/login.html
{% extends "layouts/base.html" %}
{% block title %}Masuk - PeSarana{% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

authentication/templates/signup.html
{% extends "layouts/base.html" %}
{% block title %}Daftar - PeSarana{% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <form method="post" novalidate>
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_nisn" class="form-label">NISN</label>
                            <input type="text" name="nisn" id="id_nisn"
                                   class="form-control {% if form.nisn.errors %}is-invalid{% endif %}"
                                   value="{{ form.nisn.value|default_if_none:'' }}">
                            {% for error in form.nisn.errors %}
                                <div class="invalid-feedback">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <div class="mb-3">
                            <label for="id_dob" class="form-label">Tanggal Lahir</label>
                            <input type="date" name="dob" id="id_dob"
                                   class="form-control {% if form.dob.errors %}is-invalid{% endif %}"
                                   value="{{ form.dob.value|default_if_none:'' }}">
                            {% for error in form.dob.errors %}
                                <div class="invalid-feedback">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <div class="mb-3">
                            <label for="id_email" class="form-label">Email</label>
                            <input type="email" name="email" id="id_email"
                                   class="form-control {% if form.email.errors %}is-invalid{% endif %}"
                                   value="{{ form.email.value|default_if_none:'' }}">
                            {% for error in form.email.errors %}
                                <div class="invalid-feedback">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <div class="mb-3">
                            <label for="id_password" class="form-label">Password</label>
                            <input type="password" name="password" id="id_password"
                                   class="form-control {% if form.password.errors %}is-invalid{% endif %}">
                            {% for error in form.password.errors %}
                                <div class="invalid-feedback">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <button type="submit" class="btn btn-primary w-100">Daftar</button>
                    </form>
                    <div class="mt-3 text-center">
                        <p>Sudah punya akun? <a href="href="{% url 'login' %}"">Masuk Disini</a></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/App.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}PeSarana{% endblock title %}</title>
        <link rel="stylesheet" href="{% static "vendors/bootstrap/css/bootstrap.min.css" %}">
    </head>
    <body>
        {% block layout %}{% endblock layout %}
    </body>
</html>

templates/layouts/base.html
{% extends "App.html" %}
{% block layout %}
    {% include "components/navbar.html" %}
    <main>
        {% block content %}{% endblock content %}
    </main>
    {% include "components/footer.html" %}
{% endblock layout %}

templates/layouts/dashboard.html
{% extends "App.html" %}
{% block layout %}

{% endblock layout %}